FROM debian:bookworm-slim

COPY dockerfiles/bookworm-sources.list /etc/apt/sources.list

RUN	apt-get update && apt-get install -y \
	gcc g++ build-essential make git cifs-utils sudo wget gnupg1 \
	python3 autoconf automake libtool bash locales \
	gcc-multilib g++-multilib libc6-dev

RUN apt-get install -y pkg-config
	 
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

ENV LANG en_US.UTF-8 

COPY dockerfiles/my_init /sbin/
RUN chmod +x /sbin/my_init

USER jenkins

CMD ["/sbin/my_init"]
